name: A workflow for my Hello World file
on:
  push:
    branches:
    - master
    
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
#    - uses: ./action-b
#      env:
#        MY_NAME: "Bob"


#    - name: Discord notification
#      env:
#        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#      uses: Ilshidur/action-discord@0.0.2
#      with:
#        args: 'The project has been deployed.'

#  otherjob:
#    name: This is the name of the other job
#    runs-on: ubuntu-latest
#    steps:
#    - name: Discord notification
#      env:
#        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#      uses: Ilshidur/action-discord@0.0.2
#      with:
#        args: 'The project has been deployed.'


